### ISSUE TITLE
Yolov5 Own Dataset

### ISSUE THREAD

**Issue by FiratAlabuga** [bharatsubedi/ALPR-Yolov5#2]
Hello Bharat Subedi,
First of all, thank you for your project that you developed with Yolov5 and presented on github.
I need your support on the License Plate Recognition System. Is it possible to train our own model on synthetic data?

**Comment by lerndeep** [comment]
@JFASOF Yes, you can train with your own dataset. For training models with your own dataset, prepare the Training dataset first.
Please follow the readme file for preparing the training dataset.

**Comment by bharatsubedi** [comment]
@JFASOF Yes, you can train with your own dataset. For training models with your own dataset, prepare the Training dataset first.
Please follow the readme file for preparing the training dataset. If you check inside all plate detection and character detection directory, you will understand how to prepare data for training as well.

**Comment by bharatsubedi** [comment]
@JFASOF you send me the dataset link in my private email. Your datasets are very simple so that you can get 100% accuracy easily. Just follow the steps below, your datasets have only plates so you don't need to use the plate detection model. So please just download my character_recognition weights and run yolov5 detect.py from the original yolov5 GitHub  you will get 100% accuracy. I tried and got 100% accuracy.
![image](https://user-images.githubusercontent.com/14069935/117906057-27e2fa00-b30f-11eb-8f76-a9b43bc72d29.png)
![image](https://user-images.githubusercontent.com/14069935/117906109-40531480-b30f-11eb-9b62-2f07d83a0ea3.png)
![image](https://user-images.githubusercontent.com/14069935/117906707-704ee780-b310-11eb-93c2-087d52c9e7f3.png)

**Comment by FiratAlabuga** [comment]
first detecting the plate and then detecting the characters. But there is a problem like this, each character is recognized as a single structure, is it possible to make them a series?
because the combination of all characters is plate.

In other words, just like in your github repo, select the plate area and show the character string on it. and doing this on video.
I cannot access the dataset you are running in the structure I sent. Can you forward it to me?

**Comment by bharatsubedi** [comment]
@JFASOF you can easily download the dataset from the link you sent me through private email.  combine characters into string is very simple, although you have problem just use idea from my https://github.com/bharatsubedi/FOTS_tf_efficientnet/blob/master/test.py link. As you know that this is just a coordinate shorting problem and around 10 lines of simple code can do everything.

**Comment by FiratAlabuga** [comment]
The charachter recognition data from the visuals above are the data found in your Google Drive.

How efficient can the GTX1050 ti be?

Thanks.
Best Regards.

**Comment by bharatsubedi** [comment]
@JFASOF above visualizes dataset is from https://www.kaggle.com/tustunkok/synthetic-turkish-license-plates. I just download and test with my training weight. I detected all and recognize well. you can use any type of NVIDIA_GPU for testing. I hope you can do it easily because everything is ready. Just use guidelines clearly. Although you have a problem, let me know clearly what you want don't think the complex way.

**Comment by FiratAlabuga** [comment]
Can we do this on google colab?
We can mark on the image. Is the marking on the video on the colab?

**Comment by bharatsubedi** [comment]
@JFASOF sorry I have no free time now. You can also mark videos, just pass the videos for inferencing using OpenCV and extract a frame and inference.
